#!/usr/bin/env bash

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )"

prog=$0

warn() { [ $# -gt 0 ] && echo $prog: "$@" 1>&2; }
abort() { warn "$@"; exit 1; }

usage() {
  warn "$@"
  cat <<EOT
USAGE:
  $(basename $prog) -h
  $(basename $prog) [-l] <networkid> <adid> <template>

Given a <networkid>, an <adid>, and a <template> file, which can be JSON or
YAML, writes the <template> as JSON to ContentDB to configure adunit keyword
targeting for this ad.

TEMPLATE:
  The <template> must be of the following form (as JSON):

    {
      "adunits": "<id0>,<id1>,<id2>,..."
    }

  If no adunits are targeted set the value of "adunits" in the JSON to null.

DECISIONS:
  When making decision API requests these IDs must be passed in as follows in
  the decision API POST JSON:

    {
      "placements": [
        ...
      ],
      "keywords": [
        "adunit=<id0>",
        ...
      ]
    }

OPTIONS:
  -h                Print this and exit.

ENVIRONMENT:
  ADZERK_API_KEY    Required to be set to a valid Kevel API key.
EOT
  exit;
}

hostname=
localredis=false

while getopts "h" o; do
  case "${o}" in
    h) usage ;;
    ?) abort ;;
  esac
done
shift $((OPTIND-1))

networkid=${1:?}
adid=${2:?}
template=${3:?}

[ -f "$template"  ] || abort 'template file not found'

schemaname=AdUnitTargeting
contentkey=$adid

json=$(cat "$template" |yaml2json)

{ echo "$json" |jq . >/dev/null; } || abort 'invalid template JSON'

[ -n "$ADZERK_API_KEY" ] || abort 'ADZERK_API_KEY env var not set'

curl -s \
  -H x-adzerk-apikey:$ADZERK_API_KEY \
  -d "$json" \
  https://e-${networkid}.adzerk.net/cdb/${networkid}/custom/${schemaname}/${contentkey}
